### ISSUE TITLE
Empty html report after updating to 1.3

### ISSUE THREAD

**Issue by G00fY2** [jk1/Gradle-License-Report#115]
After updating to 1.3 my HTML file only contains the static data like title and timestamp. But there are no entries in it. Version 1.2 is working fine.
I have no configuration set.

Any idea what could cause the issue or how to debug?

**Comment by guenhter** [comment]
This is because of #113

Your "defined" configurations (runtime is default) are not found. So Maybe you want to defaune "ALL" configurations with

`configurations = ALL`


TL;DR
Explaination:
There is one configuration configured by default: `configurations = ['runtime']`

In 1.12 it works the following way: 
* If the configured configurations can be found: Take the dependencies of them
* If they cannot be found: Consider all configurations as a fallback

This behaviour can be misleading, because if you really define a configuration explicitly, you don't want the fallback scenario, so the behaviour in 1.13 is

* If the configured configurations can be found: Take the dependencies of them
* If they cannot be found: No fallback configurations

I guess you are now influcenced by this new behaviour. But acutally I think this is not too bad, because now you are forced to think about which configurations you actually want to consider ... or just use `ALL` if you don't really care.

**Comment by epicstar** [comment]
IMO, my two cents is that this should be documented as required on the Github page. I had the same issue, too, and the README currently suggests it is optional when it should be required:

> Configuration described below is entirely optional.

**Comment by epicstar** [comment]
Either the documentation should be fixed, or it should work with default configs out-of-the-box (I prefer the latter).

**Comment by jk1** [comment]
It works out of the box with dependencies from `runtime` configuration. If your project derives from the defaults, well, it's up you to configure the plugin.

**Comment by epicstar** [comment]
So I have an Android project (it might work for you since you use a java project).

I ended up trying the following here:

```gradle
licenseReport {
    // Set output directory for the report data.
    // Defaults to ${project.buildDir}/reports/dependency-license.
    outputDir = "$projectDir/build/licenses"


    // Select projects to examine for dependencies.
    // Defaults to current project and all its subprojects
    projects = [project] + project.subprojects

    // Adjust the configurations to use, e.g. for Android projects.
    configurations = ['ALL']
    // Use 'ALL' to dynamically resolve all configurations:
    // configurations = ALL
}
```

I still get an empty index.html.

**Comment by jk1** [comment]
There's an explicit mention in the readme regarding android projects:

```
// Adjust the configurations to use, e.g. for Android projects.
// Use 'ALL' to dynamically resolve all configurations:
// configurations = ALL
```
Please note, that syntax is different from your example posted above.

**Comment by jk1** [comment]
We can probably detect android plugin and apply a different default though, similar to what's requested in #104.

**Comment by guenhter** [comment]
@jk1 what do you think about applying `ALL` as a default.
This would make newcomers happy, because they will (hopefully) see something from the very beginning without configuring too much.
As soon as the user digs a little deeper into the plugin, he will define his own configurations anyway.

**Comment by epicstar** [comment]
Oh wow, I didn't even notice that I got the syntax incorrect. That did fix my issue.

**Comment by jk1** [comment]
@guenhter that would bring a lot of unwanted content into the report. Most of the time people are obliged to collect a report on what's being redistributed and shipped. `runtime` is the closest thing to that when it comes to java project. `ALL` includes test dependencies, build tooling, weird detached configurations content and what not.

I'd rather agree that it may ease the onboarding for some users, but it may also harm others. Smart defaults approach, on the contrary, feels safer to me.

To make it even worse, both approaches are backward incompatible.

**Comment by guenhter** [comment]
True true.

**Comment by jk1** [comment]
Based on the following https://docs.gradle.org/3.4/release-notes.html#runtimeclasspath-used-instead-of-runtime it seems a right thing to do to switch the default to `runtimeClasspath`.
