### ISSUE TITLE
CheckLicense conflicts with Gradle dependency-locking

### ISSUE THREAD

**Issue by weiminyu** [jk1/Gradle-License-Report#150]
Gradle version: 5.5
Plugin version: 1.8

Our project locks all dependencies using Gradle's dependency-locking. This causes
the checkLicense task to fail, with an error message saying failure to resolve some
dependency in the dependencyLicenseReport configuration. We also noticed that if
--write-locks is passed to checkLicense, the task will succeed.

We worked around the problem by not locking dependencyLicenseReport:
https://github.com/google/nomulus/commit/29e4d8de051db497d85ba416da1e17e18b9a5289#diff-c197962302397baf3a4cc36463dce5ea

**Comment by jk1** [comment]
Thank you for reporting the issue.

It turned out to be not that easy to reproduce though. A test build with 
```
dependencyLocking {
    lockAllConfigurations()
}
```
doesn't emit any errors, so I assume a dynamic version with a non-recent locked state is also needed.

Let's see if I can work this around with a detached Gradle configuration. Detached configurations tend to ignore resolution policies altogether as far as I recall.
