### ISSUE TITLE
Disallowed license?

### ISSUE THREAD

**Issue by kushal256** [jk1/Gradle-License-Report#160]
Is there a way to have forbidden or disallow certain licenses?

**Comment by guenhter** [comment]
Interesting. Currently, there is no such feature, but it might be useful...

**Comment by jk1** [comment]
I believe there is: 
https://github.com/jk1/Gradle-License-Report#check-dependency-licenses

**Comment by jk1** [comment]
@guenhter you're absolutely correct about that. The thing is, license blacklisting by itself doesn't really get you anywhere. There can always be a license out there coming from the transitive dependency with arbitrary terms you can't agree with. Say, GPL-like, or a free form of a public domain license. That's why license limits are almost always white-list based.

**Comment by guenhter** [comment]
Right. I see it absolutely the same way: Also when a blacklisted license is slightly changed and therefore the rule not longer matches it, the license then passed, even it it shouldn't pass.
This cannot happen with whitelisting....

**Comment by kushal256** [comment]
Thank you for explaining this to me, I agree.

Will close this.
