### ISSUE TITLE
Introduced Flavors and Dimensions, now HTML report is empty

### ISSUE THREAD

**Issue by WarrenFaith** [jk1/Gradle-License-Report#185]
Hi,

I have introduced multiple flavors and 2 dimensions for my project. Flavors: dev, alpha, beta, store and dimensions are google and huawei.

After that I found out that my configuration seems to be wrong and my custom renderers stopped working.
I tried to check if my renderer are broken but even the build in InventoryHtmlReportRenderer shows the html structure but no parsed dependencies.

My configuration:
```
licenseReport {
   outputDir = "$projectDir/src/main/assets/licences"
   //configurations = ALL
   //configurations = ['google']
   excludeOwnGroup = false
   excludeGroups = ['...']
   excludes = ['...']
   renderers = [new InventoryHtmlReportRenderer(), new CustomHtmlReportRendererEn(), new CustomHtmlReportRendererDe()]
}
```

If I use `configuratios = ALL` I get issues with unmatched configurations. I tried all possible configurations I can imagine as well. From `googleDevRelease` to just `google` or `debug`.

Any ideas what I am doing wrong?

**Comment by jk1** [comment]
Hi,

I'd recommend running dependencies task on the problematic project to check the list of configurations you have at the moment. Since it also lists dependencies in each configuration, one should be able to select the most appropriate one for the report.

Just keep in mind that not all configurations are resolvable by Gradle. Only resolvable configurations can be used by the plugin to get dependencies from.

**Comment by MartinBreuerWetterCom** [comment]
Thanks, that was a great suggestion. I ended up by using this configuration: `googleReleaseCompileClasspath`.

Can be closed!

**Comment by WarrenFaith** [comment]
Thanks, that was a great suggestion. I ended up by using this configuration: `googleReleaseCompileClasspath`.

**Comment by jk1** [comment]
Thank you for the update.
I've added a readme section to get that issue covered.
