### ISSUE TITLE
Grouping logical Licenses

### ISSUE THREAD

**Issue by mattinger** [jk1/Gradle-License-Report#37]
I know this is mostly an issue with the downstream libraries, but it would be nice to be able to group together different license names into larger groups.

For instance, our report produces various strings for Apache licenses:

Apache 2
Apache 2.0
Apache License
...

I'd love to be able to create some sort of either regex or simple string matching based grouping so they can all be put together in the report.

**Comment by chubbard** [comment]
I like this idea.  We still have trouble with embedded licenses that embed the license text into the jar files, but this could work out of the box for common colloquial names given to licenses.

**Comment by ManfredSchenkIOSB** [comment]
Perhaps the grouping could also be done by using License URLs if available.

Since there is likely no generic solution for the different cases, a kind of aliases map may help. It should be possible to customize this map to add more aliases

**Comment by chubbard** [comment]
@ManfredSchenkIOSB I think it'll be roughly the same amount of work for the user using URLs vs defining a set of common names to collate.  License URLs are all over the map just like names.  People link to different websites, their own copies of the licenses hosted on their project pages.  But that being said it could be that we allow the user to use whatever they wish to collate: Name or License URL.  In fact I think this could be used to replace the existing way of handling Unknown licenses.  If I can get sometime to dedicate to this I would take a crack at it.

**Comment by guenhter** [comment]
@chubbard @ManfredSchenkIOSB @mattinger 
I implemented such a feature on under https://github.com/guenhter/Gradle-License-Report/tree/data-normalizer
Just see the last commit (and the bottom of the README)
Please let me know what you think before I create the pull-request.

**Comment by chubbard** [comment]
I think this is a good for sure.  I would like the implementation of the normalization to be independent from the rendering of it.  In other words, if I transform my licenses any renderer should be able to work with a normalized set.  That would make this feature more widely applicable for people who want to write their own renderers.

I want to merge the crude CSV file I created for unknown licenses with this feature, but there are some key differences in configuration.  The unknown license feature specifies down to the package level (gradle package ID, license name, license URL, project URL).  At first I thought we could combine this, but now I realize they are operating at different levels (aggregate license across many dependencies vs individual dependency level).  But to harmonize configurations between these features would be a good goal.  I suppose I need to dig into the code and see how you are implementing this.

The minor suggestions would you be open to changing "transformationInfo" to "transformationRules"?  Since in the docs you refer to them as rules I think that would harmonize the docs with the code.  What if we shorten "transformToBundleName" to simply "bundleName"?

**Comment by jk1** [comment]
@guenhter thanks a lot for putting your effort into this.
I've just introduced a new [extension point](https://github.com/jk1/Gradle-License-Report/blob/master/src/main/groovy/com/github/jk1/license/filter/DependencyFilter.groovy) for use cases like that. It seems to be a better fit for dependency grouping code.

**Comment by guenhter** [comment]
@jk1 Thanks for the change. I migrated my version to your filter. Do you think that we can make my normalizer robust enough to be merged in to your repo? When you have a look at it, you will see that it just evaluates rules which must be provided by every user of your plugin. Those rules then defines how a licence in the `ProjectData` is modified (if needed).

**Comment by guenhter** [comment]
Try out  #45 and let me know if there is any issue.

**Comment by jk1** [comment]
Pull request has been merged and released in scope of 0.6.
